spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://121.170.161.72:3306/stock101
    username: pjw1480
    password: 675401
mybatis:
  type-aliases-package: com.monstersinc.stock101.*.model.vo
  mapper-locations:
    - classpath:mappers/**/*.xml
  configuration:
    jdbc-type-for-null: NULL
springdoc:
  swagger-ui:
    operations-sorter: method
  paths-to-match:
    - /api/v1/**
#jwt:
#  issuer: https://accounts.beyond.com
#  secret: "{cipher}63ca8b3e32847b897b5ac3bbfd869e0e198bde9f183b3ff3a89e97324461022e"